{% set name = "bw2analyzer" %}
{% set version = "0.11.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2336589b1f292d64a0b1dcf95d841444146fb09de192e17aa78c1edc1e8b788b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools
  run:
    - bw2calc
    - bw2data
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.4
    - requests
    - scipy
    - stats_arrays
    - tabulate
    - tqdm

test:
  imports:
    - bw2analyzer

about:
  home: https://github.com/brightway-lca/brightway2-analyzer
  summary: Set of tools to analyze results of life cycle assessment (LCA) calculations
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/brightway-lca/brightway2-analyzer

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
